import { action, internalMutation, internalQuery } from "./_generated/server";
import { v } from "convex/values";
import { internal } from "./_generated/api";

export const sendToSlack = action({
  args: { itemId: v.id("syncItems") },
  handler: async (ctx, args) => {
    const item = await ctx.runQuery(internal.slack.getItem, {
      itemId: args.itemId,
    });
    if (!item) throw new Error("Item not found");
    if (item.status !== "analyzed") throw new Error("Item not yet analyzed");

    const webhookUrl = process.env.SLACK_WEBHOOK_URL!;

    const blocks = [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `🚀 Release Note: PR #${item.prNumber}`,
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*<${item.prUrl}|${item.prTitle}>*\nAuthor: ${item.prAuthor} | Merged: ${new Date(item.prMergedAt).toLocaleDateString()}`,
        },
      },
      ...(item.linearTicketId
        ? [
            {
              type: "section",
              text: {
                type: "mrkdwn",
                text: `🎫 *Linear:* <${item.linearUrl}|${item.linearTicketId} - ${item.linearTitle}>`,
              },
            },
          ]
        : []),
      { type: "divider" },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*🔧 Technical Summary*\n${item.technicalSummary}`,
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*💡 What This Means for Users*\n${item.businessSummary}`,
        },
      },
      ...(item.keyChanges && item.keyChanges.length > 0
        ? [
            {
              type: "section",
              text: {
                type: "mrkdwn",
                text: `*Key Changes:*\n${item.keyChanges.map((c: string) => `• ${c}`).join("\n")}`,
              },
            },
          ]
        : []),
      {
        type: "context",
        elements: [
          {
            type: "mrkdwn",
            text: `Areas: ${(item.impactedAreas ?? []).join(", ")} | Generated by Release Intelligence`,
          },
        ],
      },
    ];

    await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ blocks }),
    });

    await ctx.runMutation(internal.slack.markSent, { itemId: args.itemId });
  },
});

export const sendReleaseToSlack = action({
  args: { releaseId: v.id("releases") },
  handler: async (ctx, args) => {
    const items = await ctx.runQuery(internal.slack.getItemsByRelease, {
      releaseId: args.releaseId,
    });

    const analyzedItems = items.filter((i: any) => i.status === "analyzed");
    if (analyzedItems.length === 0) throw new Error("No analyzed items to send");

    const webhookUrl = process.env.SLACK_WEBHOOK_URL!;

    const blocks: any[] = [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `🚀 Release Report — ${analyzedItems.length} PRs`,
        },
      },
      { type: "divider" },
    ];

    for (const item of analyzedItems) {
      blocks.push(
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*<${item.prUrl}|PR #${item.prNumber}: ${item.prTitle}>*${item.linearTicketId ? ` (${item.linearTicketId})` : ""}`,
          },
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `💡 ${item.businessSummary ?? "_Pending analysis_"}`,
          },
        },
        { type: "divider" }
      );

      await ctx.runMutation(internal.slack.markSent, { itemId: item._id });
    }

    await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ blocks }),
    });
  },
});

// Internal helpers
export const getItem = internalQuery({
  args: { itemId: v.id("syncItems") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.itemId);
  },
});

export const getItemsByRelease = internalQuery({
  args: { releaseId: v.id("releases") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("syncItems")
      .withIndex("by_releaseId", (q) => q.eq("releaseId", args.releaseId))
      .collect();
  },
});

export const markSent = internalMutation({
  args: { itemId: v.id("syncItems") },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.itemId, { slackSent: true });
  },
});
